# _config.yml
title: Food Recognition App
description: Upload an image to recognize food items.
baseurl: "" # leave this empty for the root directory
url: "https://<username>.github.io" # replace <username> with your GitHub username
theme: jekyll-theme-slate # You can use other Jekyll themes or leave it blank if using plain HTML
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social Media
social:
  github: "https://github.com/<username>"
  twitter: "https://twitter.com/<username>"
  linkedin: "https://www.linkedin.com/in/<username>"
  
# Permalinks for posts or pages
permalink: /:year/:month/:day/:title/




