remote_theme: "mmistakes/minimal-mistakes@master"
plugins:
  - jekyll-remote-theme

title: "Food Recognizer"
description: "An image classification API that classifies 20 different types of caps worn around the world"
author:
  name: "Shoaib Akther Asif"

# Set baseurl depending on where the site is hosted
baseurl: "" # Leave as "" if you're using GitHub user/organization pages, or "/Capstone-project---Image-Detect" for project pages.

# Specify the docs folder for GitHub Pages
source: docs

# Include docs folder in the URL path
permalink: /:title/
