remote_theme: "mmistakes/minimal-mistakes@master"
plugins:
  - jekyll-remote-theme

title: "Food Recognizer"
description: "An image classification API that classifies 25 different types of foods"
author:
  name: "Shoaib Akther Asif"

url: "https://Shoaib-Akther-Asif.github.io"
baseurl: "/Capstone-project---Image-Detect"

# Specify the docs folder for GitHub Pages
source: docs

# Change the permalink format
permalink: /food-recognizer/

