remote_theme: "mmistakes/minimal-mistakes@master"
plugins:
  - jekyll-remote-theme

title: Food Recognizer
description: An image classification API that classifies 20 different types of caps worn around the world

author:
  name: Shoaib Akther Asif
